import { useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { completePasswordReset, requestPasswordReset, verifyPasswordResetOtp } from '../services/authApi'

export default function ResetPassword() {
  const location = useLocation(); const email = location.state?.email || sessionStorage.getItem('passwordResetEmail') || ''
  const [code, setCode] = useState(''); const [resetToken, setResetToken] = useState(''); const [password, setPassword] = useState(''); const [confirmPassword, setConfirmPassword] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function verify(event) { event.preventDefault(); setBusy(true); setError(''); try { const data = await verifyPasswordResetOtp(email, code); setResetToken(data.resetToken); setMessage('Code verified. Choose a new password.') } catch (nextError) { setError(nextError.status === 429 ? 'Too many attempts. Request another code later.' : 'The code is invalid or expired.') } finally { setBusy(false) } }
  async function complete(event) { event.preventDefault(); setError(''); if (password !== confirmPassword) return setError('Passwords do not match.'); if (password.length < 8) return setError('Password must be at least 8 characters.'); setBusy(true); try { await completePasswordReset(resetToken, password); sessionStorage.removeItem('passwordResetEmail'); setMessage('Password updated successfully. You can now sign in.'); setResetToken('COMPLETE') } catch { setError('The reset session is invalid or expired. Request a new code.') } finally { setBusy(false) } }
  async function resend() { setBusy(true); setError(''); try { await requestPasswordReset(email); setMessage('If the account is eligible, a new code has been sent.'); setCode('') } catch { setError('Unable to request another code right now.') } finally { setBusy(false) } }
  if (!email) return <div className="auth-form"><h1>Reset session missing</h1><Link to="/forgot-password">Request a reset code</Link></div>
  if (resetToken === 'COMPLETE') return <div className="auth-form"><p className="eyebrow">Password reset</p><h1>Password updated</h1><p>{message}</p><Link className="primary-button" to="/login">Sign in</Link></div>
  if (resetToken) return <form className="auth-form" onSubmit={complete}><p className="eyebrow">Secure reset</p><h1>Choose a new password</h1>{message ? <p role="status">{message}</p> : null}<label className="field-stack"><span>New password</span><input autoComplete="new-password" minLength="8" onChange={(event) => setPassword(event.target.value)} required type="password" value={password} /></label><label className="field-stack"><span>Confirm new password</span><input autoComplete="new-password" minLength="8" onChange={(event) => setConfirmPassword(event.target.value)} required type="password" value={confirmPassword} /></label>{error ? <p className="form-error" role="alert">{error}</p> : null}<button className="primary-button" disabled={busy} type="submit">{busy ? 'Updating...' : 'Update password'}</button></form>
  return <form className="auth-form" onSubmit={verify}><p className="eyebrow">Password reset</p><h1>Enter your reset code</h1><p>If an eligible account exists, a code was sent to {email}.</p><label className="field-stack"><span>Six-digit code</span><input autoComplete="one-time-code" inputMode="numeric" maxLength="6" onChange={(event) => setCode(event.target.value.replace(/\D/g, '').slice(0, 6))} required value={code} /></label>{error ? <p className="form-error" role="alert">{error}</p> : null}{message ? <p role="status">{message}</p> : null}<button className="primary-button" disabled={busy || code.length !== 6} type="submit">Verify code</button><button disabled={busy} onClick={resend} type="button">Request another code</button></form>
}
